### ISSUE TITLE
[JOSS] OSI License

### ISSUE THREAD

**Issue by HaoZeke** [giorginolab/vmd_diffusion_coefficient#1]
Hi. This is linked to the [ongoing JOSS review](https://github.com/openjournals/joss-reviews/issues/1698#event-2599680575). Please replace the text of your license file with a suitable [OSI License](https://opensource.org/licenses/alphabetical). Personally, I think the [BSD 3-clause](https://opensource.org/licenses/BSD-3-Clause) is essentially what is described by the current `LICENSE` file, but feel free to choose another or discuss it further here.

**Comment by tonigi** [comment]
Hi HaoZeke, thanks for the ongoing review! I updated the LICENSE file to the BSD-3, which is what was supposed to be all along.

**Comment by HaoZeke** [comment]
Excellent! Thanks for the prompt resolution.
