### ISSUE TITLE
Printout functionality

### ISSUE THREAD

**Issue by jrperilla** [giorginolab/vmd_diffusion_coefficient#10]
It would be nice to add a button to the GUI to call the ‘printout’ procedure, in case a user wants to write data to a specified file without resorting to exporting the data from the Multiplot window.

**Comment by tonigi** [comment]
Done in 159ff92f7229eb1aa2c39a8aeb3e480bf9b32e45 et al. , as a "save" button. Saves a CSV with tau/MSD/D and headers to reproduce the computation.
