### ISSUE TITLE
Doman error: argument not in validity range

### ISSUE THREAD

**Issue by maurosgroi** [giorginolab/vmd_diffusion_coefficient#11]
Dear developers,
I'm trying to use the plugin to process CP2K trajectory files.
They are in the xyz format and correctly read by VDM.
I run the calculation till the step 38000 so I'm trying to calculate the MSD and D between 28000 and 38000 discarding the previous steps. I selected every 500 frames and the "name Li" to focus on the only Li atom that I've in the liquid structure.

I'm obtaining the error in the object.

Could you help me to find my error and run properly the plugin?

My trajectory file is uploaded here for reference.

https://drive.google.com/file/d/1KvZz5x6FwgOP3dzH6fePghMQBineIlfE/view?usp=sharing

Thanks a lot in advance and best regards,
Mauro Sgroi.
Centro Ricerche FIAT.
Italia.

**Comment by tonigi** [comment]
Given it's a single atom, you should disable the "subtract center of mass drift" option. ;)
