### ISSUE TITLE
Selection in Diffusion Coefficient Tool

### ISSUE THREAD

**Issue by jiroegbu** [giorginolab/vmd_diffusion_coefficient#13]
Hi, good day. I have a system containing lithium and perchlorate ions, I can easily determine diffusion coefficients for lithium ion using selection as type 2 which represents lithium in my trajectory and data file. However, for perchlorate ion it is not working. I used "type 3" as selection to mean the chlorine in the perchlorate structure but it does not work. I also tried "type 3 or type 4" to mean both the chlorine and the 4 oxygen in the ion and it still did not work). What is the way around this? Thank you.

**Comment by tonigi** [comment]
What is the error?

**Comment by jiroegbu** [comment]
Each selected atom should belong to a separate molecule

**Comment by tonigi** [comment]
You have to figure out a selection which matches only one atom per molecule. That depends on your case. Upload the loaded files if further help is needed.

**Comment by jiroegbu** [comment]
I believe the type 3 selection represents the single chlorine atom in the perchlorate ion which contains one chlorine atom and 4 oxygen atoms. I have added a link to download the file I am analyzing (86mb) 

https://drive.google.com/file/d/16SDWEM23TBozODGeP9xfsHm2A9ZOdEFp/view?usp=sharing

**Comment by tonigi** [comment]
There seem to be 2 problems.
* The format does not make bonds explicit. VMD infers them, which confuses the "single molecule" detection logic.
* The trajectory is wrapped, which is a no-go for the calculation (so your result for lithium may be wrong)

**Comment by jiroegbu** [comment]
Thanks. I understand the second point. Any idea for how to fix the first?

**Comment by tonigi** [comment]
Sorry for the late reply. Have a look at VMD's functions, such as `bondsrecalc`, or `topotools`
