### ISSUE TITLE
How to install the diffusion coefficient tool?

### ISSUE THREAD

**Issue by TianmingQu** [giorginolab/vmd_diffusion_coefficient#14]
Hi all, could anyone give me some instructions on how to install the diffusion coefficient tool on vmd plugin?

**Comment by mastersubhadeep** [comment]
After you load VMD, try the following command:
source /path/to/vmd_diffusion_coefficient/load.tcl

**Comment by tonigi** [comment]
Also see comments in https://gist.github.com/tonigi/a9cfaf7642a7fbc13293
