### ISSUE TITLE
how use it to calculate osmotic permeability

### ISSUE THREAD

**Issue by groponp** [giorginolab/vmd_diffusion_coefficient#15]
Dear I'm intereset into know if it algorithm enable calculate pf (osmotic permeability) to measure water transport into aquaporins

**Comment by tonigi** [comment]
I doubt it is possible without adaptations.

**Comment by groponp** [comment]
Dear,
Sorry that the question is basic, but how can I select the water molecules that are inside a monomer of my aquaporin, since when I make a selection using for example "waters and z >=-9 and z < 9" if I do not apply an update of the selection, everything looks scattered and I don't really see the molecules in the channels, like I see them if I just do "waters".

I would appreciate any suggestions.

**Comment by tonigi** [comment]
No, currently updating the selection at every frame is not supported (because the number of atoms would change).
