### ISSUE TITLE
[JOSS] Doc Citation

### ISSUE THREAD

**Issue by HaoZeke** [giorginolab/vmd_diffusion_coefficient#2]
Hi, as part of https://github.com/openjournals/joss-reviews/issues/1698, could you update the citation in the [readme](https://github.com/giorginolab/vmd_diffusion_coefficient/tree/master/doc).

**Comment by tonigi** [comment]
Done in 04d4ab981e5350207be828dae8aa076b5c10e303 - assuming the paper will be accepted :)

**Comment by HaoZeke** [comment]
Excellent.
