### ISSUE TITLE
[JOSS] Community Guidelines (Contribution)

### ISSUE THREAD

**Issue by HaoZeke** [giorginolab/vmd_diffusion_coefficient#3]
```
Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
```
Part of https://github.com/openjournals/joss-reviews/issues/1698. I think the docs are clear on (2) and (3), so if there could be a line added to address (1) then we're good to go!

**Comment by tonigi** [comment]
Done in 4587dd512b3a2e112eea57392bddbe85d6736b82  (together with an explanation of the test case and its comparision with the experimental result). Thanks!

**Comment by HaoZeke** [comment]
Thanks for the quick resolution!
