### ISSUE TITLE
Auto_path variable issue

### ISSUE THREAD

**Issue by jrperilla** [giorginolab/vmd_diffusion_coefficient#4]
When installing the plugin, the authors note (in the README of the doc/ subdirectory of the Git repository specified in the JOSS manuscript) several methods to integrate their plugin into the VMD startup routine. I opted to append the plugin location to the auto_path variable. However, when this is done, an error is thrown to stdout by VMD upon startup. While this did not hamper the functionality of the method, both in command-line or GUI usage (including registering the plugin in the Extensions menu), it indicates a bad interface with the VMD startup script/routines and the problem should be amended. An identical error is also thrown for VMD for Windows 10, which makes sense since Tcl/Tk-only plugins are architecture-independent.

**Comment by jrperilla** [comment]
![image](https://user-images.githubusercontent.com/15744430/64998221-45995b00-d8b1-11e9-94e8-b30c858781b2.png)

**Comment by tonigi** [comment]
The script used a trick in `pkgIndex.tcl` to register itself with VMD; it was supposed to enable loading by merely setting TCLLIBPATH. However this did not work in all situations (as in your case).   I rolled back the install instructions to a more standard "append auto_path / package require / vmd register" sequence, now in `load.tcl`. b93901dc72982373faecea357fb85b428d736d24
