### ISSUE TITLE
calculating diffusion coefficient from linear fit

### ISSUE THREAD

**Issue by jrperilla** [giorginolab/vmd_diffusion_coefficient#6]
While using the GUI implementation, and selecting either of the two ‘Plot’ options, it would be beneficial to always output the diffusion coefficient from linear fit to stdout. Since the MSD calculation is expensive, I don’t see a reason not to perform the linear fit and extract the coefficient before calling the Multiplot window, even if the user did not click the separate “Diffusion coefficient from linear fit” button which launches the complete routine anyway but does not plot the MSD.

**Comment by tonigi** [comment]
Indeed the button was more a "cosmetic" choice to highlight the fact that a fit was taking place. Good point though. I changed the GUI according to the suggestion - the button is gone; D from fit is now implicitly printed and added to the plots. 46a63521cb291a130b32972ddf43082ba316420e
